### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Pandafuchs** [Granik24/Techdroid#1]
Is there a dedicated Server?

**Comment by Granik24** [comment]
You mean server files, or normal server?

**Comment by Pandafuchs** [comment]
I mean a server.jar just like in the normal minecraft. That I can run on a different PC so all my friends can connect too. Not just the "open for lan" thing.

**Comment by Granik24** [comment]
That's not created yet. I'll post it today. ;)

**Comment by Granik24** [comment]
There is it, if you will have any issues, contact me.

Server download: http://bit.ly/1IJbA59

**Comment by Pandafuchs** [comment]
The Server works like a charm =) Thank you very much!

**Comment by Granik24** [comment]
No problem, thanks for playing my modpack :)
