### ISSUE TITLE
Server Download

### ISSUE THREAD

**Issue by EinNormalerStudent** [Granik24/Techdroid#2]
Hello!

Is there a Server for the 2.0 Update? The 1.0 Server is not working anymore...

**Comment by Granik24** [comment]
Hi there, 
sorry for that, there is no server right now. I'll be back at home at 7.12.2015, so I will upload serverfiles. Sorry for that. ;)

**Comment by EinNormalerStudent** [comment]
Okay, awesome! =) 
I love the 2.0 Version btw. :D

**Comment by Granik24** [comment]
@EinNormalerStudent Thank you so much for playin my modpack. If you will have any bugs, report it here!

Version 2.1 has been released. :)
Serverfiles: http://bit.ly/1IQ8GgE
Enjoy!
